---
title: "Communication via Email"
---


Email: __gastonsanchez@berkeley.edu__

You should limit your emails to serious problems that cannot be addressed during office hours. The vast majority of questions can be answered during OH. Email should not be used for information that is readily available in course materials (syllabus, discussion forum, announcements, etc.) or from fellow students.

I do not explain course material over email and will not respond to emails with such requests. Please use office hours, or discussion section, (or schedule another time to meet with the teaching staff if you have irreconcilable conflicts with the office hours).

 

## Reading and responding email

For general emails, I will reply to general questions or concerns within 2 to 3 business days, Monday through Friday, during regular academic hours (9:00AM-5:00PM).

Please note that I do not read email between 5pm and 9am, or during the weekends. Likewise, I do not respond to emails on the weekend.

ex. If you send an email at 6pm on Friday night, you can expect that I will read it around 9am on Monday morning, and should likely receive a response by around 9am on Tuesday morning.

If, for any reason, I haven't responded to your email after four business days, please email me again. I am human, and there are times when student emails fall through the cracks inadvertently.

__I prefer to have conversations in person rather than via email__, thus allowing us to get to know each other better and fostering a more collegial learning atmosphere.

 

## Communicate in a professional manner

If you believe your situation warrants an email, please feel free to send me a professional email. E-mail communication should be courteous and respectful in manner and tone. Please do not send e-mails that are curt or demanding.

Here's a short example of an unprofessional email. Let's assume you missed an exam, for whatever reason. Do not write and say: "I missed an exam. When can I make it up?" Instead, explain why you have extenuating circumstances, and ask the teaching staff if they will allow you to make up the exam. Most likely you won't be able to make it up, but at least you are asking in a professional way.

If you are unsure of how to write an email to me or any other professor, please consult this amusing blog post that gives you a useful template:

<a href="https://medium.com/@lportwoodstacer/how-to-email-your-professor-without-being-annoying-af-cf64ae0e4087" target="_blank">https://medium.com/@lportwoodstacer/how-to-email-your-professor-without-being-annoying-af-cf64ae0e4087</a>

 

## Subject line

If you wish for your email to make it into my inbox, do not leave the subject line blank. Instead, make sure the subject of your email contains the code course and a brief explanation of the nature of the email. For example: "Stat 133-Question about Homework" or "Stat 133-Request for Meeting".

 

## Avoid these subjects

- Avoid emailing me to explain why you missed or will miss class. I usually don't need to know. If you think this is affecting your performance, then schedule a meeting with me.

- Do not email me to let me know you made a mistake in your submitted assignment. Please refer to the HW policies (see [syllabus](./syllabus.html)).

- Do not email me to ask for extra credit. Here's why: <a href="https://marktomforde.com/academic/undergraduates/NoExtraCredit.html" target="_blank">https://marktomforde.com/academic/undergraduates/NoExtraCredit.html</a>

- Above all, do not email me to engage in grade grubbing. Here's why: <a href="https://marktomforde.com/academic/undergraduates/GradeGrubbing.html" target="_blank">https://marktomforde.com/academic/undergraduates/GradeGrubbing.html</a>
 


## Scheduling a meeting

If you wish to schedule a meeting with me, your message should include at least two times when you would like to meet and a brief (one-two sentence) description of the reason for the meeting.



## Emails regarding letters of recommendation

Before you ask me to write you a letter of recommendation, please take a look at the following document: <a href="https://github.com/gastonstat/letter-of-rec" target="_blank">https://github.com/gastonstat/letter-of-rec</a>

 