---
title: "Numerical Distributions, Histograms"
subtitle: "From Lecture 15"
---

## Visualizing Categorical and Numerical Variables

- Data 6 Fall 2024
- LECTURE 15
- All about histograms and bar charts.
- Developed by students and faculty at UC Berkeley and Tuskegee University

## Variable Types and Distributions

- 1. Categorical Distributions
- 2. Bar Charts
- 3. Grouped Bar Charts
- ➤

## Variable Distributions

- Given a specific dataset, a variable has a distribution:
- For each different value of the variable, the frequency of individuals that have that value.
- Frequency: number or percent of individuals (depends on definition of “individual”; more later)
- A distribution table of the categorical variable Cookie. Each row represents a different value of Cookie.
- A bar chart that plots the distribution of the categorical variable Cookie.

## Numerical Distributions, Histograms

- 1. Review: Bar Charts
- 2. Numerical Distributions, Histograms
- 3. Choosing Bins
- 4. Overlaid and Side-by-Side Histograms
- ➤

## Towards Numerical Distributions

- Bar charts visualize the distribution of a categorical variable, or the relationship between a categorical variable and one or more numerical variables.
- Bar charts cannot display the distribution of a numerical variable.
- Question: How might we display the distribution of a numerical variable?
- Answer: One solution is to combine ranges of values into bins.

## Histograms

- A histogram visualizes the distribution of a numerical variable by binning. The method
- t.hist(column, density = False)
- creates a histogram of the column column of t. This column must contain numerical values.
- It automatically chooses bins for us. We can change them.

## Bar Charts vs. Histograms

- Bar charts visualize the distribution of a categorical variable, or the relationship between a categorical variable and a numerical variable.
- Length of bar corresponds to value.
- Width of bar means nothing.
- Histograms visualize the distribution of a numerical variable.
- Length of bar corresponds to number of values within bin.
- Width of bar corresponds to the width of the bin.
  - Wider bin → more values within bin → smoother histogram.


