---
title: "Cause and Effect"
subtitle: ""
---

## John Snow and the Broad Street Pump

::: {.callout-note title="Read _Inferential Thinking_"}
 Read [all of Chapter 2](https://inferentialthinking.com/chapters/02/causality-and-experiments.html), which describes in detail experimental setup and design.
 
 Before continuing, make sure that you are familiar with the following terminology:
 
 * observational study
 * causality
 * association
 * comparison
 * treatment group
 * control group
 * randomized controlled trial (RCT)
 
:::

In the majority of this class we will _not_ be able to conduct a randomized controlled trial. This is because the datasets we analyze are almost all **observational studies** and not experiments. As a result, in this class we seek to understand associations between variables, and we will almost never seek to establish causal relationships between variables. To understand causality, we encourage you to take inferential thinking courses like Data 8, Stat 20, and a wide range of Statistics courses.


## External Reading

* (mentioned in notes) _Computational and Inferential Thinking_, [Ch 5.1](https://inferentialthinking.com/chapters/05/1/Arrays.html)