---
title: "[Lec 22] Data 6 Fall 2024 - Sampling and Computational Social Science"
---

## Slide 1: Sampling and CSS

- Data 6 Fall 2024
- LECTURE 22
- Thinking about representation.
- Developed by students and faculty at UC Berkeley and Tuskegee University

## Slide 2: Week 13

- Quiz 2 grades will come out tomorrow night
  - A few observations:
    - Quiz 1 median: 89, mean: 81
    - Quiz 2 median: 79, mean: 78
  - Quiz 2 was more difficult than Quiz 1 (particularly the coding questions). However, there were fewer outliers.
  - Clobber policy based on the pre-midterm 2 material. Likely a z-score clobber. I’ll update the syllabus end-of-week
- We’re in the home stretch!
- Announcements!

## Slide 3: Final Project Details

- Large language models have transformed the way that we approach computational social science
- Big question: How accurately can LLMs classify/detect hate speech? Empathy? Misinformation?
- 2 Parts to the Final Project
  - Part 0: Fill out the survey due tomorrow night for partner matching. If you have someone in mind, I will do my best to honor that request.
    - Wednesday you will get started on Part 1 of the project
  - Part 1 (Assigned tonight, due November 25th)
    - Pick a dataset, as well as a CSS task
    - You’ll classify data by hand (just a little, it’s a very manual process)
  - Part 2 (Assigned November 25th, due December 9th)
    - Use LLMs to speed up this process. Investigate your findings!

## Slide 4: Today’s Roadmap

- Computational Social Science
- Sampling Approaches
- Lecture 22, Data 6 Fall 2024

## Slide 5: Computational Social Science

- ➤
- 1. Recap
- 2. Sample Setting
- 3. Biases
- 4. Sampling Approaches

## Slide 6: What is Computational Social Science?

<details><summary>Speaker notes</summary>

A little useless…

</details>

## Slide 7: What is Computational Social Science?

<details><summary>Speaker notes</summary>

Source: https://direct.mit.edu/coli/article/50/1/237/118498/Can-Large-Language-Models-Transform-Computational

</details>

## Slide 8: Language from police body camera footage shows racial disparities in officer respect

<details><summary>Speaker notes</summary>

Source: https://law.stanford.edu/wp-content/uploads/2017/06/PNAS-2017-Voigt-1702413114.pdf

</details>

## Slide 9: Language from police body camera footage shows racial disparities in officer respect

<details><summary>Speaker notes</summary>

Source: https://law.stanford.edu/wp-content/uploads/2017/06/PNAS-2017-Voigt-1702413114.pdf

</details>

## Slide 10: Predicting epidemics using search engine data: a comparative study on measles in the largest countries of Europe

<details><summary>Speaker notes</summary>

https://bmcpublichealth.biomedcentral.com/articles/10.1186/s12889-020-10106-8

</details>

## Slide 11: Class Activity

- https://direct.mit.edu/coli/article/50/1/237/118498/Can-Large-Language-Models-Transform-Computational
- Read over your assigned utterance-level and conversational-level data. How difficult do you think it would be to perform a CSS classification task with these types of data?
- Ted’s and Nikita’s Group: 3.1.1-3.1.3
- Kimberly’s and Caroline’s Group: 3.1.4-3.1.6
- Annie’s and Abi’s Group: 3.1.7-3.1.9
- Henry’s and Andy’s Group 3.1.10-3.2.1
- Abhi’s Group 3.2.2 - 3.2.4
- Marcela’s Group: 3.2.5-3.2.6

<details><summary>Speaker notes</summary>

https://direct.mit.edu/coli/article/50/1/237/118498/Can-Large-Language-Models-Transform-Computational

</details>

## Slide 12: CSS Task Overview & Discussion

- Ted & Nikita’s group
- Dialect features, emotions, figurative language
  - Dialect feature
    - Based on how they talk (diction, grammar, spelling)
  - Emotions
    - Expressive language, fear, happiness, anger
    - Anger → easy
  - Figurative language
    - Denotative meaning vs connotative meaning
      - Difficulty: depends, rhetoric devices like metaphors that are pretty easy.
      - Sarcasm could be hard

## Slide 13: CSS Task Overview & Discussion

- Hate speech, humor, ideology
- Hate speech
  - Harm individuals/group based on stereotype
    - Hard to detect → stereotypes are rooted in ideology. Is it hate speech or common sense in society?

## Slide 14: Sample Setting

- ➤
- 1. Recap
- 2. Sample Setting
- 3. Biases
- 4. Sampling Approaches

## Slide 15: Why talk about samples?

- If you want to create your own dataset, rather than use materials-based research
- Remember the concepts of external validity/generalizability!

## Slide 16: What is a Sample?

- A sample is a subset of the population used to make inferences about the overall group.
- Examples:
  - A classroom of students in a school.
    - Sample: classroom
    - Population: student body of the school
  - Picking out 10 marbles from a bag with 100 marbles.
    - Sample: 10 marbles
    - Population: bag of marbles
  - Published papers in an academic journal.
    - Sample: published papers in the journal
    - Population: all research happening in the field

## Slide 17: Motivating Question

- Why would would we need to take a sample? What are the pros and cons?

## Slide 18: Population vs. Sampling Frame vs. Sample

- Given a research question, the population is the group you want to learn something about.
  - However, directly studying the population as a whole is often not possible! Data might not exist at that scale, or it might be too costly to collect, if it’s even possible to gather that information.
- So, we want to use a sample from the population to make inferences.
  - If the sample is a good representation of the population, we can make useful analyses at a much lower cost.
- Depending on how we select our sample, we may miss individuals from the population we’re interested in, and we might also include individuals that are not in the population.
  - The list we actually draw our sample from is the sampling frame.

## Slide 19: Population vs. Sampling Frame vs. Sample

- Examples:
  - A classroom of students in a school.
    - Sample: classroom
    - Population: student body of the school
  - Picking out 10 marbles from a bag with 100 marbles.
    - Sample: 10 marbles
    - Population: bag of marbles
  - Published papers in an academic journal.
    - Sample: published papers in the journal
    - Population: all research happening in the field
- Sampling Frame: All classrooms
- Sampling Frame: All marbles
- Sampling Frame: All accessible papers

## Slide 20: Visualizing the Relationship

- Population
- Sampling Frame
- Sample

## Slide 21: Population vs. Sampling Frame vs. Sample

- Let’s say you’re planning a social event for all second-year students at your school. Since you only have the budget to cater pizza, you want to figure out what pizza toppings second-year students enjoy, and buy pizza toppings according to how popular they are.
  - Our population is second-year students. Since our social event is for second-year students, the preferences of students that are not second-years is not relevant.
- In order to figure out the most popular flavors, you survey every student walking into the cafeteria from 12 PM to 1 PM by asking what their favorite topping is. Assume that everyone responds.
  - Our sampling frame is students walking into the cafeteria between 12 and 1.

## Slide 22: Population vs. Sampling Frame vs. Sample

- If we draw a sample from this sampling frame, is our sample representative? Why or why not?
  - Not necessarily. Our survey will include the responses of students that are not second-years, who might have different preferences than the second-years.
- How can we change our sampling method to make our sample look more like our population?
  - We could send out an email to only second-year students, only record the response of second-year students, conduct the survey in more locations…
- If a sample is representative, then it looks like the population. In this case, our sample may not be very representative.
- Are our results generalizable?
  - Maybe! For example, first-year students might have similar pizza preferences, but professors might not.

## Slide 23: Key Terms

- Population: the group you want to learn something about
- Sampling frame: the list from which the sample is taken
  - Remember that this is not necessarily the same as the population!
- Sample: a subset of the sampling frame used to make inferences about the population
- Representativeness: how similar a sample is to the intended population
- Generalizability: the degree to which your results can be applied to a broader population or domain of interest, based on your sampling and data collection methods

## Slide 24: Questions?

## Slide 25: Sampling Approaches

- ➤
- 1. Recap
- 2. Sample Setting
- 3. Biases
- 4. Sampling Approaches

## Slide 26: Probabilistic Sampling Methods

## Slide 27: Simple Random Sampling

- Sample drawn uniformly at random, without replacement
- Every subset of the population has the same chance of being chosen from the sampling frame
  - Each individual has the same probability of selection as any other individual
  - Each pair has the same probability of selection as any other pair
  - Each trio has the same probability of selection as any other trio…

## Slide 28: Complex Sampling

- Stratified random sampling: Divide populations into subgroups (these are the strata) based on population characteristics, then draw random sample from each strata.
  - Characteristics within each strata should be homogenous, but characteristics between different strata should be heterogeneous
  - Requires detailed population information, which may not be readily available
  - Improves representativeness by carefully curating the makeup of the sampling frame

## Slide 29: Non-Probabilistic Sampling Methods

## Slide 30: Quota Sampling

- Quota sampling is a non-probability sampling technique where you arbitrarily select a sample that includes a specific number of samples from particular categories.
  - Example: You’re a classical musician who wants to know what piece of music other orchestra members want to play. In order to figure this out, you ask the first two violin players, first two trumpet players, first flute player, first three viola players, and first percussionist you see at rehearsal.
  - Easier to do than stratified random sampling, with similar intentions

## Slide 31: Snowball Sampling

- Snowball sampling is a non-probabilistic sampling method where existing study subjects recruit future subjects from among their acquaintances, such as through a referral program.
  - Useful when study subjects have a rare characteristic that you are interested in studying. The concept of homophily is why it’s easier to find subjects with the rare characteristic by referral.
  - This could lead to skewed results due to in-group bias and bias introduced through the non-probabilistic method of constructing the sample.

## Slide 32: Questions?

## Slide 33: Recap

- Next Time
- Computational Social Science - what is it?
- Different types of sampling
- Quick check: https://docs.google.com/forms/d/e/1FAIpQLSdjvk8kpQepzncipVJ-UIetXcz4e1NCLW3rttW3Focmxvgnaw/viewform?usp=sf\_link
- Starting the final project!

