---
title: "9) Text Mining 1"
subtitle: "UC Berkeley, STAT 133, Spring 2025"
---


## 📖 Lecture

We move on to our next topic which involves basic principles behind Text Mining, "_the process of distilling actionable insights from text_".

Broadly speaking, Text Mining analysis can be divided in two big categories: 1) Bag-of-Words (bow) analysis, and 2) Syntactic Parsing. In this course, we will focus exclusively on topics related to bag-of-words analysis.

__Preliminary Operations__: Because text data is rarely ready to be analyzed, we need to first discuss some of the common preparation steps for having text data in a way that can be mathematically/statistically analyzed.

__Frequency Analysis__: The most basic type of bag-of-words text mining analysis consists of counting the number of occurrences or frequencies of each token.



## 📚 Reading

Read chapters 1, 2 and 4 of "Text Mining with R" (by Julia Silge and David Robinson):

- <a href="https://www.tidytextmining.com/tidytext" target="_blank">https://www.tidytextmining.com/tidytext</a>
- <a href="https://www.tidytextmining.com/sentiment" target="_blank">https://www.tidytextmining.com/sentiment</a>
- <a href="https://www.tidytextmining.com/ngrams" target="_blank">https://www.tidytextmining.com/ngrams</a>



## 🔬 Lab

- Publish a shiny app to <a href="https://www.shinyapps.io/" target="_blank">shinyapps.io</a>
- Keep practicing regular expressions.

 

## 🎯 Objectives

- List at least four operations that are commonly applied to a text data set before it can be analyzed with text mining techniques.
- Describe the notion of stopwords.
- Explain what a corpus (or corpora) is.
- Explain what a token is.
- Explain the concept of tokenization.
- Compute frequencies of tokens.
- Visualize frequencies with barcharts and wordclouds.



## 🔔 Assignments

- Midterm on Friday 10/25
- Keep working on your shiny App1, due 11/01

