---
title: "1) Intro"
subtitle: "UC Berkeley, STAT 133, Spring 2025"
---


## 📖 Lecture

Welcome to Stat 133. Our first meeting is on Wednesday Jan-22 where we begin with the usual review of the course policies, logistics, overall expectations, topics in a nutshell, etc. As for Friday Jan-24 we start with an introduction to R vectors which are the most basic kind of data structure in R.

 

## 🔬 Lab

On Thursday Jan-23 you'll get started with R and RStudio: first, we want to make sure everybody has installed both programs; and then we will provide an introductory review of RStudio’s workspace, as well as a brief intro to Quarto notebooks. 

BTW: there's nothing to submit this week.

 

## 🔔 Activities

If you haven't yet, please spend some time outside class to review the following documentation:

- <a href="../syllabus.html" target="_blank">syllabus</a>
- <a href="../email.html" target="_blank">communication via email</a>
- <a href="../faqs.html" target="_blank">some frequently asked questions</a>
- <a href="../five-things.html" target="_blank">five things you need to know to pass this class</a>
- <a href="https://forms.gle/FVpF8e9cSRBLBBvFA" target="_blank">introduction survey (google form)</a>



## 📢 Install R & RStudio

For those of you that don't have either R or RStudio, download and install these programs (both are free, and they are available for Mac, Windows, and Linux computers)

- <a href="https://cran.r-project.org/" target="_blank">Install R</a>

- <a href="https://www.rstudio.com/products/rstudio/download/#download" target="_blank">Install RStudio</a> (Desktop free version)

