---
title: "10) Text Mining 2"
subtitle: "UC Berkeley, STAT 133, Spring 2025"
---


## 📖 Lecture

One popular topic in text mining involves __Sentiment Analysis__ (aka Sentiment Scoring).
Simply put, sentiment analysis is the process of extracting an author's emotional intent from text. At first glance, sentiment analysis may appear easy. But as we will see, this type of analysis is tricky to do well. There are various emotional frameworks that can be used for sentiment analysis. We will cover a simple approach that implies stating whether a document is positive, negative, or neutral. This is referred to as the polarity of a document.



## 📚 Reading

Read chapters 1, 2 and 4 of "Text Mining with R" (by Julia Silge and David Robinson):

- <a href="https://www.tidytextmining.com/sentiment" target="_blank">https://www.tidytextmining.com/sentiment</a>



## 🔬 Lab

- Getting started with the `"tidytext"` package.



## 🎯 Objectives

- Define sentiment analysis.
- Describe a basic polarity scoring algorithm.
- Compute basic sentiments (positive, negative, neutral) of a text.



## 🔔 Assignments

- Shiny App1, due 11/01
- Shiny App2 released on 11/02, due 11/14