---
title: "6) Tables and Tidyverse-2"
subtitle: "UC Berkeley, STAT 133, Spring 2025"
---


## 📖 Lecture

This week we continue with another fundamental tidyverse package `"dplyr"`. Simply put, **dplyr** comes with functions that allow you to manipulate data-tables (e.g. data-frames, and other 2-dimensional objects) using a modern and syntactic way.

 

## 📚 Reading

Read chapters 5 to 10 of "R Tidy Hurricanes":

- <a href="https://www.gastonsanchez.com/R-tidy-hurricanes/2-02-intro-dplyr.html" target="_blank">https://www.gastonsanchez.com/R-tidy-hurricanes/2-02-intro-dplyr.html</a>
- <a href="https://www.gastonsanchez.com/R-tidy-hurricanes/2-03-intro-pipes.html" target="_blank">https://www.gastonsanchez.com/R-tidy-hurricanes/2-03-intro-pipes.html</a>
- <a href="https://www.gastonsanchez.com/R-tidy-hurricanes/3-01-storms-year.html" target="_blank">https://www.gastonsanchez.com/R-tidy-hurricanes/3-01-storms-year.html</a>
- <a href="https://www.gastonsanchez.com/R-tidy-hurricanes/3-02-storms-1975.html" target="_blank">https://www.gastonsanchez.com/R-tidy-hurricanes/3-02-storms-1975.html</a>
- <a href="https://www.gastonsanchez.com/R-tidy-hurricanes/3-03-amy-1975.html" target="_blank">https://www.gastonsanchez.com/R-tidy-hurricanes/3-03-amy-1975.html</a>
- <a href="https://www.gastonsanchez.com/R-tidy-hurricanes/3-04-summary-1975.html" target="_blank">https://www.gastonsanchez.com/R-tidy-hurricanes/3-04-summary-1975.html</a>



## 🔬 Lab

You will get to practice common manipulation operations of data-tables using a modern and syntactic way following the data plying framework provided by the R package dplyr.

Time permitting, we'll also review various aspects that have to do with reading in (i.e. importing) tables in R.



## 🎯 Objectives

Perform basic manipulations on data tables with "dplyr" functions:

- Select rows with `slice()`, and `filter()`
- Select columns with `select()`
- Transform columns with `mutate()`
- Arrange rows with `arrange()`
- Group data with `group_by()`
- Summarize data with `summarize()`



## 🔆 Shiny Friday

The shiny app for this week uses the `mtcars` data set to visualize the top-n cars given a selected variable.

- __mtcars-topn-barchart__: produces a simple barchart---via `"ggplot2"`---to visualize the top-n cars given a selected variable. In addition to the plot, it also displays a table with the top-n cars. More important, this app uses a so-called __reactive conductor__ element.<br>
<a href="https://github.com/data133/shiny/tree/main/mtcars-topn-barchart" target="_blank">https://github.com/data133/shiny/tree/main/mtcars-topn-barchart</a>



## 🔔 Assignments

- HW4 due this 2/28
- HW5 released on 3/01, due 3/07
