---
title: "7) Iterations"
subtitle: "UC Berkeley, STAT 133, Spring 2025"
---


## 📖 Lecture

In addition to writing functions to reduce duplication in your code, you also need to learn about iteration, which helps you when you need to do the same operation several times. Namely, we review control flow structures such as for loops, while loops, repeat loops, and the apply family functions.

 


## 📚 Reading

Read chapters 13 and 14 of "R Coding Basics":

- <a href="https://www.gastonsanchez.com/R-coding-basics/5-04-for-loop.html" target="_blank">https://www.gastonsanchez.com/R-coding-basics/5-04-for-loop.html</a>
- <a href="https://www.gastonsanchez.com/R-coding-basics/5-05-while-loop.html" target="_blank">https://www.gastonsanchez.com/R-coding-basics/5-05-while-loop.html</a>



## 🔬 Lab

You’ll keep working writing a variety of loops in R (e.g. for, while, repeat).

 

## 🎯 Objectives

At the end of this week you will be able to:

- Write for loops to repeat the same operation a given number of times
- Write while loops to repeat the same operation an unknown number of times



## 🔆 Shiny Friday

The shiny app for this week is the same one from last week: it uses `mtcars` data set to visualize the top-n cars given a selected variable.

An important component of this app is the use of the `reactive()` function to create so-called __reactive conductors__ (i.e. an R expression that uses widget input(s) and returns a value).

- __mtcars-topn-barchart__: produces a simple barchart---via `"ggplot2"`---to visualize the top-n cars given a selected variable. In addition to the plot, it also displays a table with the top-n cars. More important, this app uses a so-called __reactive conductor__ element.<br>
<a href="https://github.com/data133/shiny/tree/main/mtcars-topn-barchart" target="_blank">https://github.com/data133/shiny/tree/main/mtcars-topn-barchart</a>



## 🔔 Assignments

- HW5 due this 3/07
- HW6 released on 3/08, due 3/14
